name: Blog deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2   

    - name: Update the repo from web server
      uses: appleboy/ssh-action@v0.1.4      
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        CI: false
      with:
        host: ${{ secrets.WEB_SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIV_KEY }}
        envs: CI, NODE_OPTIONS
        script: |
          cd ~/blog.notional.ventures
          git stash save --keep-index --include-untracked
          git pull
          export PATH=/root/.nvm/versions/node/v18.9.0/bin/:$PATH

          if ! [ $? -eq 0 ]; then
              echo "git pull failed with errors."
              exit 1
          fi

          npm install
          npm run build
