name: Main deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update the repo from web server
      uses: appleboy/ssh-action@v0.1.7
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        CI: false
        ANALYZE: true
      with:
        host: ${{ secrets.WEB_SERVER_2 }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIV_KEY }}
        envs: CI, NODE_OPTIONS
        script: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github@web-server-2
          cd ~/CNWeb30-Backend
          export PATH=/root/.nvm/versions/node/v19.1.0/bin/:$PATH
          git stash save --keep-index --include-untracked
          git pull

          if ! [ $? -eq 0 ]; then
              echo "git pull failed with errors."
              exit 1
          fi

          cp cn-web-backend.service /etc/systemd/system/cn-web-backend.service
          systemctl stop cn-web-backend.service
          systemctl daemon-reload
          echo "Service file copied!"

          npm install

          if [ $? -eq 0 ]; then
              systemctl restart cn-web-backend.service
              systemctl is-active --quiet cn-web-backend.service && echo "Web Backend server restarted successfully." || (echo "Web Backend server failed to restart." && exit 1)
          else
              echo "npm run build failed with error. Stopped restarting the web server."
              exit 1
          fi
